name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # หรือ branch ที่ Great ใช้

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # เปลี่ยน version ได้ตามโปรเจกต์

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: sogreatsg.fun  # ถ้าใช้ custom domain
